security:
    providers:
        default:
            id: App\Security\UserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            webauthn:
                failure_handler: 'App\Security\AuthenticationFailureHandler'
                success_handler: 'App\Security\AuthenticationSuccessHandler'
                registration:
                    enabled: true
                    profile: default
                    routes:
                        options_path: '/api/register/options'
                        result_path: '/api/register'
                authentication:
                    enabled: true
                    profile: default
                    routes:
                        options_path: '/api/login/options'
                        result_path: '/api/login'
            logout:
                path: '/api/logout'
                success_handler: 'App\Security\LogoutSuccessHandler'

    access_control:
        - { path: ^/attestation,  roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: 'https' }
        - { path: ^/assertion,  roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: 'https' }
        - { path: ^/api/logout,  roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: 'https' }
        - { path: ^/api/login,  roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: 'https' }
        - { path: ^/api/register,  roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: 'https' }
        - { path: ^/api/profile, roles: ROLE_USER, requires_channel: 'https' }
        - { path: ^/,       roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: 'https' }
