webauthn:
    credential_repository: 'App\Repository\PublicKeyCredentialSourceRepository'
    user_repository: 'App\Repository\PublicKeyCredentialUserEntityRepository'
    token_binding_support_handler: 'Webauthn\TokenBinding\IgnoreTokenBindingHandler'
    creation_profiles:
        default:
            rp:
                name: 'Webauthn Demo'
                id: '%env(RP_ID)%'
    request_profiles:
        default:
            rp_id: '%env(RP_ID)%'
    transport_binding_profile:
        creation:
            default:
                user_entity_repository: App\Repository\PublicKeyCredentialUserEntityRepository
                credential_source_repository: App\Repository\PublicKeyCredentialSourceRepository
                profile_name: 'default'
                request_path: '/attestation/options'
                response_path: '/attestation/result'
                session_parameter_name: '__WEBAUTHN_ATTESTATION_REQUEST__1'
        request:
            default:
                user_entity_repository: App\Repository\PublicKeyCredentialUserEntityRepository
                credential_source_repository: App\Repository\PublicKeyCredentialSourceRepository
                profile_name: 'default'
                request_path: '/assertion/options'
                response_path: '/assertion/result'
                session_parameter_name: '__WEBAUTHN_ASSERTION_REQUEST__'
    metadata_service:
        enabled: true
        repository: 'App\Repository\MetadataStatementRepository'
        enforce_verification: true
        request_factory: 'nyholm.psr7.psr17_factory'
