webauthn_security:
    http_message_factory: 'Symfony\Bridge\PsrHttpMessage\Factory\DiactorosFactory'

webauthn:
    credential_repository: 'App\Repository\PublicKeyCredentialSourceRepository'
    user_repository: 'App\Repository\PublicKeyCredentialUserEntityRepository'
    token_binding_support_handler: 'Webauthn\TokenBinding\TokenBindingNotSupportedHandler'
    android_safetynet:
        enabled: true
        api_key: '%env(API_KEY)%'
        http_client: 'httplug.client.app'
    creation_profiles:
        default:
            public_key_credential_parameters: #Mandatory
                - !php/const Webauthn\PublicKeyCredentialParameters::ALGORITHM_ES256 #Order is important. Preferred algorithms go first
                - !php/const Webauthn\PublicKeyCredentialParameters::ALGORITHM_RS256
            rp:
                name: 'Webauthn Demo'
                #id: '%env(RP_ID)%'
                #icon: null
            #challenge_length: 32
            #timeout: 60000
            #authenticator_selection_criteria:
                #attachment_mode: !php/const Webauthn\AuthenticatorSelectionCriteria::AUTHENTICATOR_ATTACHMENT_NO_PREFERENCE
                #attachment_mode: !php/const Webauthn\AuthenticatorSelectionCriteria::AUTHENTICATOR_ATTACHMENT_PLATFORM
                #attachment_mode: !php/const Webauthn\AuthenticatorSelectionCriteria::AUTHENTICATOR_ATTACHMENT_CROSS_PLATFORM
                #require_resident_key: false
                #user_verification: !php/const Webauthn\AuthenticatorSelectionCriteria::USER_VERIFICATION_REQUIREMENT_PREFERRED
                #user_verification: !php/const Webauthn\AuthenticatorSelectionCriteria::USER_VERIFICATION_REQUIREMENT_REQUIRED
                #user_verification: !php/const Webauthn\AuthenticatorSelectionCriteria::USER_VERIFICATION_REQUIREMENT_DISCOURAGED
            #attestation_conveyance: !php/const Webauthn\PublicKeyCredentialCreationOptions::ATTESTATION_CONVEYANCE_PREFERENCE_NONE
            attestation_conveyance: !php/const Webauthn\PublicKeyCredentialCreationOptions::ATTESTATION_CONVEYANCE_PREFERENCE_DIRECT
            #attestation_conveyance: !php/const Webauthn\PublicKeyCredentialCreationOptions::ATTESTATION_CONVEYANCE_PREFERENCE_INDIRECT
            #extensions: ~
    request_profiles:
        default: ~
            #rp_id: '%env(RP_ID)%'
            #challenge_length: 32
            #timeout: 60000
            #user_verification: !php/const Webauthn\AuthenticatorSelectionCriteria::USER_VERIFICATION_REQUIREMENT_PREFERRED
            #user_verification: !php/const Webauthn\AuthenticatorSelectionCriteria::USER_VERIFICATION_REQUIREMENT_REQUIRED
            #user_verification: !php/const Webauthn\AuthenticatorSelectionCriteria::USER_VERIFICATION_REQUIREMENT_DISCOURAGED
            #extensions:
                #txtAuthSimple: 'Hello World!'
                #uvm: true
                #loc: true
                #uvi: true
