webauthn:
    #http_client: ~
    #request_factory: ~
    credential_repository: 'App\Repository\PublicKeyCredentialSourceRepository'
    user_repository: 'App\Repository\PublicKeyCredentialUserEntityRepository'
    creation_profiles:
        default:
            rp:
                name: 'Webauthn Demo'
                id: '%env(RP_ID)%'
            challenge_length: 32
            timeout: 60000
    request_profiles:
        default:
            rp_id: '%env(RP_ID)%'
    controllers:
        enabled: true
        creation:
            additional_authenticator:
                options_path: '/profile/authenticators/add/options'
                result_path: '/profile/authenticators/add'
                user_entity_guesser: 'Webauthn\Bundle\Security\Guesser\CurrentUserEntityGuesser'
    metadata:
        enabled: true
        mds_repository: 'App\Repository\MetadataStatementRepository'
        status_report_repository: 'App\Repository\StatusReportRepository'
        #certificate_chain_checker: 'App\Security\CertificateChainChecker'
