# Please see the following page for more information: https://webauthn-doc.spomky-labs.com/the-webauthn-server/the-symfony-way#configuration

webauthn:
    credential_repository: 'App\Repository\PublicKeyCredentialSourceRepository'
    user_repository: 'App\Repository\PublicKeyCredentialUserEntityRepository'
    creation_profiles:
        default:
            rp:
                name: '%env(RELAYING_PARTY_NAME)%' # Please adapt the env file with the correct relaying party ID or set null
                id: '%env(RELAYING_PARTY_ID)%' # Please adapt the env file with the correct relaying party ID or set null
            challenge_length: 32
            timeout: 60000
    request_profiles:
        default:
            rp_id: '%env(RELAYING_PARTY_ID)%' # Please adapt the env file with the correct relaying party ID or set null
    controllers:
        enabled: true
        creation:
            additional_authenticator:
                options_path: '/profile/authenticators/add/options'
                result_path: '/profile/authenticators/add'
                user_entity_guesser: 'Webauthn\Bundle\Security\Guesser\CurrentUserEntityGuesser'
    metadata:
        enabled: true
        mds_repository: 'App\Repository\MetadataStatementRepository'
        status_report_repository: 'App\Repository\StatusReportRepository'
        #certificate_chain_checker: 'App\Security\CertificateChainChecker'
