webauthn:
    credential_repository: 'App\Repository\PublicKeyCredentialSourceRepository'
    user_repository: 'App\Repository\PublicKeyCredentialUserEntityRepository'
    creation_profiles:
        default:
            rp:
                name: 'Webauthn Demo'
                id: '%env(RP_ID)%'
            challenge_length: 32
            timeout: 60000
    request_profiles:
        default:
            rp_id: '%env(RP_ID)%'
    controllers:
        enabled: true
        creation:
            additional_authenticator:
                options_path: '/profile/authenticators/add/options'
                result_path: '/profile/authenticators/add'
                user_entity_guesser: 'Webauthn\Bundle\Security\Guesser\CurrentUserEntityGuesser'
    metadata_service:
        enabled: true
        repository: 'App\Repository\MetadataStatementRepository'
    certificate_chain_checker:
        enabled: true
        http_client: '@nyholm.psr7.psr17_factory'
        request_factory: '@nyholm.psr7.psr18_factory'
