webauthn:
    credential_repository: 'App\Repository\PublicKeyCredentialSourceRepository'
    user_repository: 'App\Repository\PublicKeyCredentialUserEntityRepository'
    token_binding_support_handler: 'Webauthn\TokenBinding\IgnoreTokenBindingHandler'
    android_safetynet:
        enabled: true
        api_key: '%env(API_KEY)%'
        http_client: 'httplug.client.app'
    creation_profiles:
        default:
            public_key_credential_parameters: #Mandatory
                - !php/const Cose\Algorithms::COSE_ALGORITHM_ES256 #Order is important. Preferred algorithms go first
                - !php/const Cose\Algorithms::COSE_ALGORITHM_RS256
            rp:
                name: 'Webauthn Demo'
                id: '%env(RP_ID)%'
                #icon: null
            #challenge_length: 32
            #timeout: 60000
            #authenticator_selection_criteria:
                #attachment_mode: !php/const Webauthn\AuthenticatorSelectionCriteria::AUTHENTICATOR_ATTACHMENT_NO_PREFERENCE
                #attachment_mode: !php/const Webauthn\AuthenticatorSelectionCriteria::AUTHENTICATOR_ATTACHMENT_PLATFORM
                #attachment_mode: !php/const Webauthn\AuthenticatorSelectionCriteria::AUTHENTICATOR_ATTACHMENT_CROSS_PLATFORM
                #require_resident_key: false
                #user_verification: !php/const Webauthn\AuthenticatorSelectionCriteria::USER_VERIFICATION_REQUIREMENT_PREFERRED
                #user_verification: !php/const Webauthn\AuthenticatorSelectionCriteria::USER_VERIFICATION_REQUIREMENT_REQUIRED
                #user_verification: !php/const Webauthn\AuthenticatorSelectionCriteria::USER_VERIFICATION_REQUIREMENT_DISCOURAGED
            #attestation_conveyance: !php/const Webauthn\PublicKeyCredentialCreationOptions::ATTESTATION_CONVEYANCE_PREFERENCE_NONE
            #attestation_conveyance: !php/const Webauthn\PublicKeyCredentialCreationOptions::ATTESTATION_CONVEYANCE_PREFERENCE_DIRECT
            attestation_conveyance: !php/const Webauthn\PublicKeyCredentialCreationOptions::ATTESTATION_CONVEYANCE_PREFERENCE_INDIRECT
            #extensions: ~
    request_profiles:
        default:
            rp_id: '%env(RP_ID)%'
            #challenge_length: 32
            #timeout: 60000
            #user_verification: !php/const Webauthn\AuthenticatorSelectionCriteria::USER_VERIFICATION_REQUIREMENT_PREFERRED
            #user_verification: !php/const Webauthn\AuthenticatorSelectionCriteria::USER_VERIFICATION_REQUIREMENT_REQUIRED
            #user_verification: !php/const Webauthn\AuthenticatorSelectionCriteria::USER_VERIFICATION_REQUIREMENT_DISCOURAGED
            #extensions:
                #txtAuthSimple: 'Hello World!'
                #uvm: true
                #loc: true
                #uvi: true
#    transport_binding_profile:
#        creation:
#            default:
#                profile_name: 'default'
#                request_path: '/attestation/options'
#                response_path: '/attestation/result'
#                host: '%env(RP_ID)%'
#                session_parameter_name: '__WEBAUTHN_ATTESTATION_REQUEST__1'
#        request:
#            default:
#                profile_name: 'default'
#                request_path: '/assertion/options'
#                response_path: '/assertion/result'
#                host: '%env(RP_ID)%'
#                session_parameter_name: '__WEBAUTHN_ASSERTION_REQUEST__'
